import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { AuthContextProvider } from "./auth/_util/auth-context";
import { CartProvider } from "./context/CartProvider";
import MiniCart from "../components/MiniCart";
import Footer from "../components/Footer"; // 👈 import footer
import { ThemeToggle } from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeToggle>
          <CartProvider>
            <AuthContextProvider>
              <Navbar />
              <main>{children}</main>
              <Footer />
              <MiniCart />
            </AuthContextProvider>
          </CartProvider>
        </ThemeToggle>
      </body>
    </html>
  );
}
