// lib/products.js
// Expanded mock data array with discounts

//ChatGPT helped us create this data array
/*
Prompt: Create a mock data array of 60 products for an online liquor store. Each product should have the following properties: id, name, slug, price, image, abv (alcohol by volume), size, category (Whisky, Vodka, Wine, Beer, Rum, Tequila), origin (country), description. Ensure a mix of different categories and origins. Include realistic values for each property. Additionally, add a discount property to some products to indicate a percentage discount on the original price.
*/

export const PRODUCTS = [
  // ===== WHISKY =====
  {
    id: "lagavulin-16",
    name: "Lagavulin 16 Year Single Malt",
    slug: "lagavulin-16",
    price: 159.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Iconic Islay single malt with peat smoke and dried fruit.",
    discount: 0
  },
  {
    id: "macallan-12",
    name: "Macallan 12 Year",
    slug: "macallan-12",
    price: 89.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Smooth single malt with notes of vanilla and oak.",
    discount: 10
  },
  {
    id: "jack-daniels",
    name: "Jack Daniel's Old No.7",
    slug: "jack-daniels",
    price: 29.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "USA",
    description: "Famous Tennessee whiskey with notes of caramel and vanilla.",
    discount: 0
  },
  {
    id: "chivas-regal",
    name: "Chivas Regal 12 Year",
    slug: "chivas-regal",
    price: 49.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Blended Scotch whisky with rich honey and fruit flavors.",
    discount: 0
  },
  {
    id: "glenfiddich-18",
    name: "Glenfiddich 18 Year",
    slug: "glenfiddich-18",
    price: 119.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Rich and complex single malt.",
    discount: 0
  },
  {
    id: "tullamore-dew",
    name: "Tullamore Dew",
    slug: "tullamore-dew",
    price: 27.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Ireland",
    description: "Triple-distilled Irish whiskey, light and fruity.",
    discount: 5
  },
  {
    id: "glenlivet-12",
    name: "Glenlivet 12 Year",
    slug: "glenlivet-12",
    price: 39.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Smooth and fruity single malt.",
    discount: 0
  },
  {
    id: "balvenie-doublewood-12",
    name: "Balvenie DoubleWood 12 Year",
    slug: "balvenie-doublewood-12",
    price: 59.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Aged in two types of wood for rich flavor.",
    discount: 0
  },
  {
    id: "aberlour-16",
    name: "Aberlour 16 Year",
    slug: "aberlour-16",
    price: 129.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Sherry cask matured with rich flavors.",
    discount: 0
  },
  {
    id: "hennessy-vs",
    name: "Hennessy VS Cognac",
    slug: "hennessy-vs",
    price: 59.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "France",
    description: "Rich cognac with notes of oak and vanilla.",
    discount: 15
  },

  // ===== VODKA =====
  {
    id: "grey-goose",
    name: "Grey Goose Vodka",
    slug: "grey-goose",
    price: 49.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "France",
    description: "Smooth premium vodka.",
    discount: 0
  },
  {
    id: "absolut",
    name: "Absolut Vodka",
    slug: "absolut",
    price: 25.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Sweden",
    description: "Classic vodka with a smooth, neutral taste.",
    discount: 0
  },
  {
    id: "belvedere",
    name: "Belvedere Vodka",
    slug: "belvedere",
    price: 39.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Poland",
    description: "Luxury vodka with a smooth creamy finish.",
    discount: 0
  },
  {
    id: "ketel-one",
    name: "Ketel One Vodka",
    slug: "ketel-one",
    price: 31.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Netherlands",
    description: "Premium Dutch vodka, crisp and clean taste.",
    discount: 0
  },
  {
    id: "grey-goose-2",
    name: "Grey Goose Vodka Special",
    slug: "grey-goose-2",
    price: 54.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "1L",
    category: "Vodka",
    origin: "France",
    description: "Limited edition smooth premium vodka.",
    discount: 5
  },
  {
    id: "absolut-vodka-citron",
    name: "Absolut Vodka Citron",
    slug: "absolut-vodka-citron",
    price: 28.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Sweden",
    description: "Citrus flavored vodka, fresh and zesty.",
    discount: 7
  },
  {
    id: "stoli",
    name: "Stolichnaya Vodka",
    slug: "stoli",
    price: 26.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Russia",
    description: "Classic Russian vodka with smooth finish.",
    discount: 0
  },
  {
    id: "titos",
    name: "Tito's Handmade Vodka",
    slug: "titos",
    price: 32.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "USA",
    description: "Gluten-free vodka with clean taste.",
    discount: 0
  },
  {
    id: "chopin",
    name: "Chopin Potato Vodka",
    slug: "chopin",
    price: 44.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Poland",
    description: "Creamy and smooth potato vodka.",
    discount: 0
  },
  {
    id: "smirnoff",
    name: "Smirnoff No.21",
    slug: "smirnoff",
    price: 19.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Russia",
    description: "Popular classic vodka.",
    discount: 0
  },

  // ===== WINE =====
  {
    id: "apothic-red",
    name: "Apothic Red Blend",
    slug: "apothic-red",
    price: 13.99,
    image:"/placeholderProduct.jpg",
    abv: "13.5%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Bold red with dark fruit, mocha and vanilla notes.",
    discount: 0
  },
  {
    id: "prophecy-merlot",
    name: "Prophecy Merlot",
    slug: "prophecy-merlot",
    price: 15.99,
    image:"/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Soft and smooth Merlot with notes of plum and blackberry.",
    discount: 0
  },
  {
    id: "cabernet-sauvignon",
    name: "Cabernet Sauvignon Reserve",
    slug: "cabernet-sauvignon",
    price: 21.99,
    image:"/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Rich red wine with bold tannins and dark fruit.",
    discount: 0
  },
  {
    id: "santa-margarita",
    name: "Santa Margarita Pinot Grigio",
    slug: "santa-margarita",
    price: 18.99,
    image:"/placeholderProduct.jpg",
    abv: "12%",
    size: "750 ml",
    category: "Wine",
    origin: "Italy",
    description: "Fresh and crisp white wine with citrus notes.",
    discount: 0
  },
  {
    id: "merlot-reserve",
    name: "Merlot Reserve",
    slug: "merlot-reserve",
    price: 16.99,
    image:"/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Velvety red wine with plum and blackberry notes.",
    discount: 0
  },
  {
    id: "pinot-noir",
    name: "Pinot Noir Reserve",
    slug: "pinot-noir",
    price: 24.99,
    image:"/placeholderProduct.jpg",
    abv: "13%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Smooth red wine with cherry and spice notes.",
    discount: 5
  },
  {
    id: "moet-chandon",
    name: "Moet & Chandon Brut",
    slug: "moet-chandon",
    price: 49.99,
    image:"/placeholderProduct.jpg",
    abv: "12%",
    size: "750 ml",
    category: "Wine",
    origin: "France",
    description: "Classic sparkling wine, crisp and elegant.",
    discount: 0
  },
  {
    id: "chardonnay-reserve",
    name: "Chardonnay Reserve",
    slug: "chardonnay-reserve",
    price: 17.99,
    image:"/placeholderProduct.jpg",
    abv: "13%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Bright and crisp with subtle oak notes.",
    discount: 0
  },
  {
    id: "riesling-estate",
    name: "Riesling Estate",
    slug: "riesling-estate",
    price: 14.99,
    image:"/placeholderProduct.jpg",
    abv: "12%",
    size: "750 ml",
    category: "Wine",
    origin: "Germany",
    description: "Light, fruity, and aromatic white wine.",
    discount: 0
  },
  {
    id: "zinfandel-reserve",
    name: "Zinfandel Reserve",
    slug: "zinfandel-reserve",
    price: 22.99,
    image:"/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Rich red wine with spice and berry flavors.",
    discount: 0
  },

  // ===== BEER =====
  {
    id: "heineken",
    name: "Heineken Lager",
    slug: "heineken",
    price: 2.99,
    image: "/placeholderProduct.jpg",
    abv: "5%",
    size: "330 ml",
    category: "Beer",
    origin: "Netherlands",
    description: "Crisp and refreshing lager.",
    discount: 0
  },
  {
    id: "guinness",
    name: "Guinness Draught",
    slug: "guinness",
    price: 3.49,
    image: "/placeholderProduct.jpg",
    abv: "4.2%",
    size: "440 ml",
    category: "Beer",
    origin: "Ireland",
    description: "Smooth creamy stout.",
    discount: 0
  },
  {
    id: "budweiser",
    name: "Budweiser",
    slug: "budweiser",
    price: 1.99,
    image: "/placeholderProduct.jpg",
    abv: "5%",
    size: "355 ml",
    category: "Beer",
    origin: "USA",
    description: "Classic American lager.",
    discount: 0
  },
  {
    id: "corona",
    name: "Corona Extra",
    slug: "corona",
    price: 2.49,
    image: "/placeholderProduct.jpg",
    abv: "4.6%",
    size: "355 ml",
    category: "Beer",
    origin: "Mexico",
    description: "Light and crisp Mexican beer.",
    discount: 0
  },
  {
    id: "stella-artois",
    name: "Stella Artois",
    slug: "stella-artois",
    price: 2.79,
    image: "/placeholderProduct.jpg",
    abv: "5%",
    size: "330 ml",
    category: "Beer",
    origin: "Belgium",
    description: "Premium European lager.",
    discount: 0
  },
  {
    id: "blue-moon",
    name: "Blue Moon Belgian White",
    slug: "blue-moon",
    price: 3.29,
    image: "/placeholderProduct.jpg",
    abv: "5.4%",
    size: "355 ml",
    category: "Beer",
    origin: "USA",
    description: "Wheat beer with orange peel flavor.",
    discount: 0
  },
  {
    id: "samuel-adams",
    name: "Samuel Adams Boston Lager",
    slug: "samuel-adams",
    price: 3.19,
    image: "/placeholderProduct.jpg",
    abv: "5%",
    size: "355 ml",
    category: "Beer",
    origin: "USA",
    description: "Full-bodied lager with balanced hops.",
    discount: 0
  },
  {
    id: "coors-light",
    name: "Coors Light",
    slug: "coors-light",
    price: 1.89,
    image: "/placeholderProduct.jpg",
    abv: "4.2%",
    size: "355 ml",
    category: "Beer",
    origin: "USA",
    description: "Light and crisp beer.",
    discount: 0
  },
  {
    id: "pilsner-urquell",
    name: "Pilsner Urquell",
    slug: "pilsner-urquell",
    price: 2.99,
    image: "/placeholderProduct.jpg",
    abv: "4.4%",
    size: "330 ml",
    category: "Beer",
    origin: "Czech Republic",
    description: "Crisp, golden pilsner.",
    discount: 0
  },
  {
    id: "newcastle-brown-ale",
    name: "Newcastle Brown Ale",
    slug: "newcastle-brown-ale",
    price: 2.69,
    image: "/placeholderProduct.jpg",
    abv: "4.7%",
    size: "355 ml",
    category: "Beer",
    origin: "UK",
    description: "Smooth and malty brown ale.",
    discount: 0
  },

  // ===== RUM =====
  {
    id: "bacardi-white",
    name: "Bacardi Superior White Rum",
    slug: "bacardi-white",
    price: 19.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Puerto Rico",
    description: "Light and smooth white rum.",
    discount: 0
  },
  {
    id: "captain-morgan",
    name: "Captain Morgan Spiced Rum",
    slug: "captain-morgan",
    price: 22.99,
    image: "/placeholderProduct.jpg",
    abv: "35%",
    size: "750 ml",
    category: "Rum",
    origin: "USA",
    description: "Spiced rum with smooth finish.",
    discount: 0
  },
  {
    id: "mount-gay",
    name: "Mount Gay Eclipse",
    slug: "mount-gay",
    price: 24.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Barbados",
    description: "Rich and smooth rum with vanilla notes.",
    discount: 0
  },
  {
    id: "myers-rum",
    name: "Myers's Original Dark Rum",
    slug: "myers-rum",
    price: 21.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Jamaica",
    description: "Full-bodied dark rum.",
    discount: 0
  },
  {
    id: "ron-zacapa",
    name: "Ron Zacapa 23",
    slug: "ron-zacapa",
    price: 59.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Guatemala",
    description: "Premium aged rum with rich flavor.",
    discount: 0
  },
  {
    id: "pyrat",
    name: "Pyrat XO Reserve",
    slug: "pyrat",
    price: 54.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Caribbean",
    description: "Sweet and complex rum.",
    discount: 5
  },
  {
    id: "appleton-estate",
    name: "Appleton Estate Signature Blend",
    slug: "appleton-estate",
    price: 29.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Jamaica",
    description: "Balanced and aromatic rum.",
    discount: 0
  },
  {
    id: "foursquare",
    name: "Foursquare Rum",
    slug: "foursquare",
    price: 34.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Rum",
    origin: "Barbados",
    description: "Rich rum with molasses notes.",
    discount: 0
  },
  {
    id: "el-dorado-12",
    name: "El Dorado 12 Year Rum",
    slug: "el-dorado-12",
    price: 49.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "Guyana",
    description: "Deep and flavorful aged rum.",
    discount: 0
  },
  {
    id: "sailor-jerry",
    name: "Sailor Jerry Spiced Rum",
    slug: "sailor-jerry",
    price: 20.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Rum",
    origin: "USA",
    description: "Bold spiced rum with vanilla notes.",
    discount: 0
  },

  // ===== TEQUILA =====
  {
    id: "patron-silver",
    name: "Patrón Silver Tequila",
    slug: "patron-silver",
    price: 19.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Crisp, smooth tequila made from 100% Weber Blue Agave.",
    discount: 0
  },
  {
    id: "don-julio-blanco",
    name: "Don Julio Blanco",
    slug: "don-julio-blanco",
    price: 29.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Smooth and crisp silver tequila.",
    discount: 0
  },
  {
    id: "casamigos-blanco",
    name: "Casamigos Blanco",
    slug: "casamigos-blanco",
    price: 34.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Crisp, smooth tequila with citrus notes.",
    discount: 0
  },
  {
    id: "espolon-reposado",
    name: "Espolón Reposado",
    slug: "espolon-reposado",
    price: 24.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Aged tequila with rich vanilla notes.",
    discount: 0
  },
  {
    id: "herradura-silver",
    name: "Herradura Silver",
    slug: "herradura-silver",
    price: 22.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Smooth and slightly sweet silver tequila.",
    discount: 0
  },
  {
    id: "milagro-silver",
    name: "Milagro Silver",
    slug: "milagro-silver",
    price: 21.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Fresh and crisp silver tequila.",
    discount: 0
  },
  {
    id: "cabo-wabo-blanco",
    name: "Cabo Wabo Blanco",
    slug: "cabo-wabo-blanco",
    price: 25.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Bright and smooth tequila.",
    discount: 0
  },
  {
    id: "1800-reposado",
    name: "1800 Reposado Tequila",
    slug: "1800-reposado",
    price: 27.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Balanced reposado with oak notes.",
    discount: 5
  },
  {
    id: "patron-anejo",
    name: "Patrón Añejo",
    slug: "patron-anejo",
    price: 49.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Rich aged tequila with caramel notes.",
    discount: 0
  },
  {
    id: "don-julio-anejo",
    name: "Don Julio Añejo",
    slug: "don-julio-anejo",
    price: 59.99,
    image:"/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Añejo tequila with smooth, rich flavors.",
    discount: 0
  }
];

// return all products
export function getAllProducts() {
  return PRODUCTS;
}

// return product by slug
export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}
