// lib/products.js
// Small mock data array for demo

export const PRODUCTS = [
  {
    id: "lagavulin-16",
    name: "Lagavulin 16 Year Single Malt",
    slug: "lagavulin-16",
    price: 159.99,

    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Iconic Islay single malt with peat smoke and dried fruit.",
  },
  {
    id: "grey-goose",
    name: "Grey Goose Vodka",
    slug: "grey-goose",
    price: 49.99,

    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "France",
  },
  {
    id: "apothic-red",
    name: "Apothic Red Blend",
    slug: "apothic-red",
    price: 13.99,

    abv: "13.5%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Bold red with dark fruit, mocha and vanilla notes.",
  },

  {
    id: "jack-daniels",
    name: "Jack Daniel's Old No.7",
    slug: "jack-daniels",
    price: 29.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "USA",
    description: "Famous Tennessee whiskey with notes of caramel and vanilla.",
  },
  {
    id: "absolut",
    name: "Absolut Vodka",
    slug: "absolut",
    price: 25.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Sweden",
    description: "Classic vodka with a smooth, neutral taste.",
  },
  {
    id: "prophecy-merlot",
    name: "Prophecy Merlot",
    slug: "prophecy-merlot",
    price: 15.99,
    image: "/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Soft and smooth Merlot with notes of plum and blackberry.",
  },
  {
    id: "chivas-regal",
    name: "Chivas Regal 12 Year",
    slug: "chivas-regal",
    price: 49.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Blended Scotch whisky with rich honey and fruit flavors.",
  },
  {
    id: "bacardi-black",
    name: "Bacardi Black Rum",
    slug: "bacardi-black",
    price: 22.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Puerto Rico",
    description: "Dark rum with smooth vanilla and molasses notes.",
  },
  {
    id: "bombay-sapphire",
    name: "Bombay Sapphire Gin",
    slug: "bombay-sapphire",
    price: 34.99,
    image: "/placeholderProduct.jpg",
    abv: "47%",
    size: "750 ml",
    category: "Whisky",
    origin: "UK",
    description: "Premium gin with delicate botanicals.",
  },
  {
    id: "santa-margarita",
    name: "Santa Margarita Pinot Grigio",
    slug: "santa-margarita",
    price: 18.99,
    image: "/placeholderProduct.jpg",
    abv: "12%",
    size: "750 ml",
    category: "Wine",
    origin: "Italy",
    description: "Fresh and crisp white wine with citrus notes.",
  },
  {
    id: "grey-goose-2",
    name: "Grey Goose Vodka Special",
    slug: "grey-goose-2",
    price: 54.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "1L",
    category: "Vodka",
    origin: "France",
    description: "Limited edition smooth premium vodka.",
  },
  {
    id: "cabernet-sauvignon",
    name: "Cabernet Sauvignon Reserve",
    slug: "cabernet-sauvignon",
    price: 21.99,
    image: "/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Rich red wine with bold tannins and dark fruit.",
  },

  // 10 more products
  {
    id: "macallan-12",
    name: "Macallan 12 Year",
    slug: "macallan-12",
    price: 89.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Smooth single malt with notes of vanilla and oak.",
  },
  {
    id: "tullamore-dew",
    name: "Tullamore Dew",
    slug: "tullamore-dew",
    price: 27.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "Ireland",
    description: "Triple-distilled Irish whiskey, light and fruity.",
  },
  {
    id: "belvedere",
    name: "Belvedere Vodka",
    slug: "belvedere",
    price: 39.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Poland",
    description: "Luxury vodka with a smooth creamy finish.",
  },
  {
    id: "ketel-one",
    name: "Ketel One Vodka",
    slug: "ketel-one",
    price: 31.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Netherlands",
    description: "Premium Dutch vodka, crisp and clean taste.",
  },
  {
    id: "moet-chandon",
    name: "Moet & Chandon Brut",
    slug: "moet-chandon",
    price: 49.99,
    image: "/placeholderProduct.jpg",
    abv: "12%",
    size: "750 ml",
    category: "Wine",
    origin: "France",
    description: "Classic sparkling wine, crisp and elegant.",
  },
  {
    id: "pinot-noir",
    name: "Pinot Noir Reserve",
    slug: "pinot-noir",
    price: 24.99,
    image: "/placeholderProduct.jpg",
    abv: "13%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Smooth red wine with cherry and spice notes.",
  },
  {
    id: "hennessey-vs",
    name: "Hennessy VS Cognac",
    slug: "hennessey-vs",
    price: 59.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Whisky",
    origin: "France",
    description: "Rich cognac with notes of oak and vanilla.",
  },
  {
    id: "absolut-vodka-citron",
    name: "Absolut Vodka Citron",
    slug: "absolut-vodka-citron",
    price: 28.99,
    image: "/placeholderProduct.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Vodka",
    origin: "Sweden",
    description: "Citrus flavored vodka, fresh and zesty.",
  },
  {
    id: "merlot-reserve",
    name: "Merlot Reserve",
    slug: "merlot-reserve",
    price: 16.99,
    image: "/placeholderProduct.jpg",
    abv: "14%",
    size: "750 ml",
    category: "Wine",
    origin: "USA",
    description: "Velvety red wine with plum and blackberry notes.",
  },
  {
    id: "glendronach-12",
    name: "Glendronach 12 Year",
    slug: "glendronach-12",
    price: 79.99,
    image: "/placeholderProduct.jpg",
    abv: "43%",
    size: "750 ml",
    category: "Whisky",
    origin: "Scotland",
    description: "Sherry cask matured single malt with rich flavors.",
  },

  {
    id: "patron-silver",
    name: "Patrón Silver Tequila",
    slug: "patron-silver",
    price: 19.99,
    image:
      "https://www.patrontequila.com/binaries/content/gallery/patrontequila/products/patron-silver/v3/story-asset-2.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Tequila",
    origin: "Mexico",
    description: "Crisp, smooth tequila made from 100% Weber Blue Agave.",
  },

  {
    id: "baileys-irish-cream",
    name: "Baileys Irish Cream",
    slug: "baileys-irish-cream",
    price: 24.99,
    image:
      "https://aem.lcbo.com/content/dam/lcbo/products/0/0/5/9/005959-A.jpg.thumb.1280.1280.jpg",
    abv: "40%",
    size: "750 ml",
    category: "Liqueur",
    origin: "Ireland",
    description: "Creamy blend of Irish whiskey and dairy cream.",
  },
];

// return all products
export function getAllProducts() {
  return PRODUCTS;
}

// return product by slug
export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}
